### ISSUE TITLE
Help flag prints out formatting strings rather than help info

### ISSUE THREAD

**Issue by OverlordQ** [k-nuth/kth-legacy#42]
```
(knuth) ovrlrdq@alpha:~/projects/knuth$ ./kth -h

%-73s

%-73s
%-73s

Options (named):

%-20s %-52s
%-20s %-52s
%-20s %-52s
%-20s %-52s
%-20s %-52s
%-20s %-52s
%-20s %-52s
%-20s %-52s
%-20s %-52s
```

**Comment by fpelliccioni** [comment]
Could you please provide platform information, installation instructions you followed and installation logs?
Thank you!

**Comment by fpelliccioni** [comment]
> Could you please provide platform information, installation instructions you followed and installation logs?
> Thank you!

It is not necessary, I have been able to verify it locally.

**Comment by fpelliccioni** [comment]
Will be fixed in next release.

**Comment by fpelliccioni** [comment]
Fixed in https://github.com/k-nuth/kth/releases/tag/v0.9.1
