### ISSUE TITLE
May 2021 BCH Upgrade & Licenses 

### ISSUE THREAD

**Issue by scherrey** [k-nuth/kth-legacy#43]
I don't see a license file in the repos - what license is K-nuth available under?

Also, has support for the May 2021 BCH Upgrade been implemented, specifically: 

1) removal of [unconfirmed transaction limits](https://bitcoincashresearch.org/t/chip-unconfirmed-transaction-chain-limit/302) 

2) support for [multiple OP_RETURNs](
https://github.com/ActorForth/Auction-Protocol/blob/main/CHIP-2021-03-12_Multiple_OP_RETURN_for_Bitcoin_Cash.md) 

Apologies if this has been addressed publicly. I'm just recently aware of this project (which looks promising and we'd like to add support for it in our [BCH-toolkit ](https://github.com/ActorForth/BCH-toolkit) project) and couldn't easily find this information.

**Comment by fpelliccioni** [comment]
> I don't see a license file in the repos - what license is K-nuth available under?

Hey thanks for noticing that!
Knuth node is released under MIT license
I just fixed it: https://github.com/k-nuth/kth/tree/master#license

> Also, has support for the May 2021 BCH Upgrade been implemented, specifically:
> 
> 1. removal of [unconfirmed transaction limits](https://bitcoincashresearch.org/t/chip-unconfirmed-transaction-chain-limit/302)
> 2. support for [multiple OP_RETURNs](https://github.com/ActorForth/Auction-Protocol/blob/main/CHIP-2021-03-12_Multiple_OP_RETURN_for_Bitcoin_Cash.md)

Yes, Knuth node supports both points, although it is worth clarifying that both points do not imply changes in the consensus.

> Apologies if this has been addressed publicly. I'm just recently aware of this project (which looks promising and we'd like to add support for it in our [BCH-toolkit ](https://github.com/ActorForth/BCH-toolkit) project) and couldn't easily find this information.

No worries, ask anything you need. Interesting project, I'm going to take a look at it
